# ===========================================
# WB Education Task Management System
# Spring Boot 3.3.5 + H2 Database + JPA
# ===========================================

# 서버 설정
server:
  port: 8080

# Spring 설정
spring:
  # 애플리케이션 정보
  application:
    name: wb-edutask
  
  # H2 데이터베이스 설정
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
  
  # H2 콘솔 설정 (개발용)
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
        trace: false
  
  # JPA/Hibernate 설정
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        use_sql_comments: true
    open-in-view: false
  
  # Jackson JSON 설정
  jackson:
    serialization:
      write-dates-as-timestamps: false
      indent-output: true
    deserialization:
      fail-on-unknown-properties: false
  
  # Redis 설정 (Docker Redis 사용)
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      timeout: 2000ms
      client-type: jedis

# 로깅 설정
logging:
  level:
    com.wb.edutask: INFO
    org.springframework.data.redis: INFO
    org.springframework.scheduling: INFO
    org.hibernate.SQL: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# 관리 엔드포인트 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,redis
  endpoint:
    health:
      show-details: always

# 애플리케이션 정보
info:
  app:
    name: WB Education Task Management System
    description: 교육 업무 관리 시스템
    version: 1.0.0
    encoding: UTF-8
    java:
      version: '@java.version@'
